# Generated by Django 2.2.17 on 2020-12-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treenav", "0002_auto_20151001_1646"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
